version: '3.7'
services:
  elassandra-db:
    image: strapdata/elassandra:6.2.3.6
    volumes:
      - elassandra-volume:/var/lib/cassandra
    ports:
      - "9042:9042"
      - "9200:9200"
    deploy:
      replicas: 1

  postgres-db:
    image: postgres:10
    deploy:
      replicas: 1
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      pg-network:
        aliases:
          - postgres

  pg-admin:
    image: dpage/pgadmin4
    deploy:
      replicas: 1
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - pg-network

volumes:
  elassandra-volume:
  postgres-volume:

networks:
  pg-network:
