version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - backend
    depends_on:
    - elassandra
  elassandra:
    image: strapdata/elassandra:6.2.3.6
    volumes:
    - elassandra-data:/var/lib/cassandra
    networks:
    - backend

volumes:
  elassandra-data:
    external: true

networks:
  backend: