version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    networks:
    - backend
    depends_on:
    - mongo-db

  mongo-db:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db
    networks:
      backend:
        aliases:
        - mongodb

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    links:
    - mongo-db:mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
    - backend

volumes:
  mongo-data:
    external:
      name: mongo-data

networks:
  backend:
