version: '3.2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - backend
    depends_on:
    - mongodb
    restart: on-failure

  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
    - mongo-data:/data/db
    networks:
    - backend

volumes:
  mongo-data:

networks:
  backend:
