version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - backend
    depends_on:
    - elassandra
    - postgres
    restart: on-failure

  elassandra:
    image: strapdata/elassandra:6.2.3.6
    volumes:
    - elassandra-data:/var/lib/cassandra
    networks:
    - backend

  postgres:
    image: postgres:10
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
    - backend

volumes:
  elassandra-data:
    external: true
  postgres-data:
    external: true

networks:
  backend: