version: '3.7'
services:
  cassandra-db:
    image: strapdata/elassandra:6.2.3.6
    volumes:
      - elassandra-volume:/var/lib/cassandra
    ports:
      - "9042:9042"
      - "9200:9200"

volumes:
  elassandra-volume: