version: '3.2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - backend
    depends_on:
    - elassandra-seed
    restart: on-failure
    environment:
      CASSANDRA_CONTACT_POINTS: "elassandra-seed,elassandra-node"
      ELASTICSEARCH_JEST_URIS: "http://elassandra-seed:9200,http://elassandra-node:9200"

  elassandra-seed:
    image: strapdata/elassandra:6.2.3.6
    volumes:
    - elassandra-data:/var/lib/cassandra
    networks:
    - backend

  elassandra-node:
    image: strapdata/elassandra:6.2.3.6
    volumes:
    - elassandra-node-storage:/var/lib/cassandra
    networks:
    - backend
    depends_on:
    - elassandra-seed
    environment:
    - "CASSANDRA_SEEDS=elassandra-seed"
    restart: on-failure

  prometheus:
    image: prom/prometheus:latest
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
    depends_on:
    - server
    networks:
    - backend
    volumes:
    - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    depends_on:
    - prometheus
    networks:
    - backend
    volumes:
    - grafana-storage:/var/lib/grafana

volumes:
  elassandra-data:
    external: true
  elassandra-node-storage:
  grafana-storage:

networks:
  backend: