version: '3.2'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - backend
    depends_on:
    - elassandra
    - postgres
    restart: on-failure

  elassandra:
    image: strapdata/elassandra:6.2.3.6
    volumes:
    - elassandra-data:/var/lib/cassandra
    networks:
    - backend

  postgres:
    image: postgres:10
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
    - backend

  prometheus:
    image: prom/prometheus:latest
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
    depends_on:
    - server
    networks:
    - backend
    volumes:
    - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    depends_on:
    - prometheus
    networks:
    - backend
    volumes:
    - grafana-storage:/var/lib/grafana

volumes:
  elassandra-data:
    external: true
  postgres-data:
    external: true
  grafana-storage:

networks:
  backend: