version: '3.7'
services:
  cassandra-db:
    image: cassandra:3.11
    volumes:
      - cassandra-volume:/var/lib/cassandra
    ports:
      - "9042:9042"
    deploy:
      replicas: 1
    restart: on-failure

  postgres-db:
    image: postgres:10
    deploy:
      replicas: 1
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      pg-network:
        aliases:
          - postgres
    restart: on-failure

  pg-admin:
    image: dpage/pgadmin4
    deploy:
      replicas: 1
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - pg-network

volumes:
  cassandra-volume:
  postgres-volume:

networks:
  pg-network:
