version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - backend
    depends_on:
    - mongodb
    restart: on-failure

  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/db
    networks:
    - backend
    - mongo-network

  mongo-express:
    image: mongo-express:latest
    ports:
    - "8081:8081"
    depends_on:
    - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
    - mongo-network

volumes:
  mongo-data:

networks:
  backend:
  mongo-network:
